# Generated by Django 3.1.7 on 2021-04-11 15:39

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('contact', models.CharField(max_length=15, verbose_name='contact')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
            ],
            options={
                'verbose_name': '| Area alerts - response',
            },
        ),
        migrations.CreateModel(
            name='home_evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('contact', models.CharField(max_length=15, verbose_name='contact')),
                ('time_frame', models.CharField(max_length=100, verbose_name='time frame')),
                ('property_type', models.CharField(max_length=100, verbose_name='property type')),
                ('property_size', models.CharField(max_length=100, verbose_name='property size')),
                ('property_age', models.CharField(max_length=100, verbose_name='property age')),
                ('lawsuit', models.CharField(max_length=100, verbose_name='lawsuit')),
                ('bedrooms', models.IntegerField(verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='bathrooms')),
                ('basement', models.CharField(max_length=100, verbose_name='basement type')),
                ('garage', models.CharField(max_length=100, verbose_name='garage capacity')),
                ('message', models.CharField(max_length=400, verbose_name='message')),
            ],
            options={
                'verbose_name': '| Home Evaluation - response',
            },
        ),
        migrations.CreateModel(
            name='pre_construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('contact', models.CharField(max_length=15, verbose_name='contact')),
                ('property_type', models.CharField(max_length=100, verbose_name='property type')),
                ('price_range', models.CharField(max_length=100, verbose_name='price range')),
                ('time_frame', models.CharField(max_length=100, verbose_name='time frame')),
                ('is_realtor', models.CharField(max_length=10, verbose_name='is a realtor')),
                ('works_with_realtor', models.CharField(max_length=10, verbose_name='works with a realtor')),
            ],
            options={
                'verbose_name': '| Pre construction - response',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Project name')),
                ('project_location', models.CharField(max_length=100, verbose_name='Project location')),
                ('project_cover', models.ImageField(upload_to='Covers')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('starts_at', models.IntegerField(verbose_name='Starts at')),
                ('project_visibility', models.BooleanField(editable='true', verbose_name='Hidden project')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
    ]
