# Generated by Django 3.1.7 on 2021-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='starts_at',
        ),
        migrations.AddField(
            model_name='pre_construction',
            name='referrer_project',
            field=models.CharField(default='Pre-construction', max_length=10, verbose_name='works with a realtor'),
            preserve_default=False,
        ),
    ]
