# Generated by Django 3.1.7 on 2021-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210412_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='referred_pre_construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='firstname')),
                ('primary_email', models.EmailField(max_length=100, verbose_name='email')),
                ('primary_number', models.CharField(max_length=15, verbose_name='contact')),
                ('desired_location', models.CharField(max_length=15, verbose_name='contact')),
                ('desired_property_type', models.CharField(max_length=100, verbose_name='property type')),
                ('desired_price_range', models.CharField(max_length=100, verbose_name='price range')),
                ('timeline_to_purchase', models.CharField(max_length=100, verbose_name='time frame')),
                ('are_you_a_realtor', models.CharField(max_length=10, verbose_name='is a realtor')),
                ('are_you_working_with_a_realtor', models.CharField(max_length=50, verbose_name='works with a realtor')),
                ('referrer_project', models.CharField(max_length=50, verbose_name='Form submitted from')),
            ],
            options={
                'verbose_name': '| Project referrals : Pre construction - response',
            },
        ),
        migrations.RemoveField(
            model_name='pre_construction',
            name='referrer_project',
        ),
    ]
