# Generated by Django 3.1.7 on 2021-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210412_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referred_pre_construction',
            options={'verbose_name': '| Project referrals : Pre construction response'},
        ),
        migrations.AddField(
            model_name='project',
            name='starts_at',
            field=models.IntegerField(default=0, verbose_name='Starting price range'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='bathrooms',
            field=models.CharField(max_length=2, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='bedrooms',
            field=models.CharField(max_length=2, verbose_name='bedrooms'),
        ),
    ]
