# Generated by Django 3.1.7 on 2021-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210413_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': '| Subscriptions',
            },
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='basement',
            field=models.CharField(blank=True, max_length=100, verbose_name='basement type'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='bathrooms',
            field=models.CharField(blank=True, max_length=2, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=2, verbose_name='bedrooms'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='garage',
            field=models.CharField(blank=True, max_length=100, verbose_name='garage capacity'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='lawsuit',
            field=models.CharField(blank=True, max_length=100, verbose_name='lawsuit'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='message',
            field=models.CharField(blank=True, max_length=400, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='property_age',
            field=models.CharField(blank=True, max_length=100, verbose_name='property age'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='property_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='property size'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='home_evaluation',
            name='time_frame',
            field=models.CharField(blank=True, max_length=100, verbose_name='time frame'),
        ),
        migrations.AlterField(
            model_name='pre_construction',
            name='price_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='price range'),
        ),
        migrations.AlterField(
            model_name='pre_construction',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='pre_construction',
            name='time_frame',
            field=models.CharField(blank=True, max_length=100, verbose_name='time frame'),
        ),
        migrations.AlterField(
            model_name='referred_pre_construction',
            name='desired_location',
            field=models.CharField(blank=True, max_length=15, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='referred_pre_construction',
            name='desired_price_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='price range'),
        ),
        migrations.AlterField(
            model_name='referred_pre_construction',
            name='desired_property_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='referred_pre_construction',
            name='referrer_project',
            field=models.CharField(blank=True, max_length=50, verbose_name='Form submitted from'),
        ),
        migrations.AlterField(
            model_name='referred_pre_construction',
            name='timeline_to_purchase',
            field=models.CharField(blank=True, max_length=100, verbose_name='time frame'),
        ),
    ]
