# Generated by Django 3.1.7 on 2021-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210420_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '| Subscription'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lastname',
        ),
        migrations.AddField(
            model_name='subscription',
            name='contact',
            field=models.CharField(blank=True, max_length=15, verbose_name='contact'),
        ),
    ]
